# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grey Vugrin
email: greyvugrin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Grey Vugrin – web developer, part-time designer, weekend volleyball player.
  I enjoy putting my mind at work to solve business problems with technology. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://greyvugrin.github.io" # the base hostname & protocol for your site
twitter_username: gindex90
github_username:  greyvugrin
linkedin_username:  grey-vugrin-60aa3755

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]
gems:
  - jekyll-seo-tag
